name: Security Scan

on: push
jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t dmi-tcat:${{ github.sha }}
      
    - uses: Azure/container-scan@v0
      with:
        image-name: dmi-tcat:${{ github.sha }}
